name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install packages 
      run: sudo apt-get install -y cmake build-essential libgtest-dev libeigen3-dev 
    - name: Build gtest
      run: sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz && sudo tar xf release-1.7.0.tar.gz && cd googletest-release-1.7.0 && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo make && sudo cp -a include/gtest /usr/include && sudo cp -a libgtest_main.so libgtest.so /usr/lib/  
    - name: Configure EidNN
      run:  mkdir build && cd build && cmake -DTESTEIDNN=ON ..
    - name: Build
      run: cd build && make
    - name: Run Tests
      run: ./build/lib/runTests 
